name: restaurant
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <=3.3.8"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.7.0
  flutter_staggered_grid_view: ^0.6.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.3.0
  go_router: ^7.0.0
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  analyzer: ^5.10.0

  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.2
  json_serializable: ^6.6.1
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/json/
    - assets/images/
    - assets/lottie/
